export const WORD_PAIRS = [
    // --- EASY ---
    ["Apple", "Pear"],
    ["Cat", "Dog"],
    ["Coffee", "Tea"],
    ["Sun", "Moon"],
    ["Car", "Truck"],
    ["Ocean", "Lake"],
    ["Pen", "Pencil"],
    ["Chair", "Sofa"],
    ["Shirt", "T-Shirt"],
    ["Shoes", "Boots"],
    ["Football", "Basketball"],
    ["Fork", "Spoon"],
    ["Doctor", "Nurse"],
    ["King", "Queen"],
    ["Gold", "Silver"],
    ["Milk", "Juice"],
    ["Door", "Window"],
    ["Phone", "Tablet"],
    ["Laptop", "Desktop"],
    ["Train", "Bus"],
    ["Plane", "Helicopter"],
    ["House", "Apartment"],
    ["River", "Stream"],
    ["Rain", "Snow"],
    ["Hot", "Cold"],

    // --- MEDIUM ---
    ["Facebook", "Twitter"],
    ["Superman", "Batman"],
    ["Guitar", "Violin"],
    ["Beer", "Wine"],
    ["McDonald's", "Burger King"],
    ["Harry Potter", "Lord of the Rings"],
    ["Tennis", "Badminton"],
    ["Piano", "Keyboard"],
    ["Taxi", "Uber"],
    ["Hotel", "Motel"],
    ["Netflix", "YouTube"],
    ["Instagram", "Snapchat"],
    ["iOS", "Android"],
    ["Marvel", "DC"],
    ["Coke", "Pepsi"],
    ["Star Wars", "Star Trek"],
    ["Visa", "Mastercard"],
    ["Harvard", "Yale"],
    ["Tokyo", "Kyoto"],
    ["New York", "Los Angeles"],
    ["Rome", "Athens"],
    ["Dolphin", "Whale"],
    ["Lion", "Tiger"],
    ["Eagle", "Falcon"],
    ["Shark", "Crocodile"],
    ["Rose", "Tulip"],
    ["Diamond", "Ruby"],
    ["Poker", "Blackjack"],
    ["Skiing", "Snowboarding"],
    ["Surf", "Skate"],

    // --- TRICKY ---
    ["Love", "Like"],
    ["Crocodile", "Alligator"],
    ["Butter", "Margarine"],
    ["Perfume", "Cologne"],
    ["Glasses", "Sunglasses"],
    ["Turtle", "Tortoise"],
    ["Biscuit", "Cookie"],
    ["Jam", "Jelly"],
    ["Rabbit", "Hare"],
    ["Bee", "Wasp"],
    ["Muffin", "Cupcake"],
    ["Pancake", "Waffle"],
    ["Tangerine", "Orange"],
    ["Lemon", "Lime"],
    ["Soup", "Stew"],
    ["Boat", "Ship"],
    ["Street", "Road"],
    ["Clock", "Watch"],
    ["Jacket", "Coat"],
    ["Hat", "Cap"],
    ["Stairs", "Ladder"],
    ["Pill", "Tablet"],
    ["Fog", "Mist"],
    ["Thunder", "Lightning"],
    ["Cave", "Tunnel"],
    ["Bridge", "Tunnel"],
    ["Prison", "Jail"],
    ["Thief", "Robber"],
    ["Smile", "Laugh"],
    ["Cry", "Sob"],

    // --- PLACES/OBJECTS ---
    ["London", "Paris"],
    ["Beach", "Pool"],
    ["School", "College"],
    ["Library", "Bookstore"],
    ["Cinema", "Theater"],
    ["Zoo", "Aquarium"],
    ["Museum", "Gallery"],
    ["Park", "Garden"],
    ["Kitchen", "Restaurant"],
    ["Bedroom", "Hotel Room"],
    ["Bar", "Club"],
    ["Church", "Cathedral"],
    ["Castle", "Palace"],
    ["Tent", "Cabin"],
    ["Market", "Supermarket"],
    ["Pharmacy", "Hospital"],

    // --- CONCEPTS/ABSTRACT ---
    ["Dream", "Nightmare"],
    ["Success", "Victory"],
    ["Genius", "Intelligent"],
    ["Rich", "Wealthy"],
    ["Ghost", "Spirit"],
    ["Knowledge", "Wisdom"],
    ["Talent", "Skill"],
    ["Luck", "Destiny"],
    ["Fear", "Anxiety"],
    ["Hope", "Faith"],
    ["War", "Battle"],
    ["Peace", "Silence"],
    ["Law", "Rule"],
    ["Fact", "Truth"],
    ["Error", "Mistake"],
    ["Problem", "Puzzle"],
    ["Secret", "Mystery"],
    ["Magic", "Illusion"],
    ["Art", "Design"],
    ["Music", "Noise"]
];
